name: '[docker] CI for build tests'

on: workflow_dispatch

jobs:
    test:
        if: github.repository == 'DIYgod/RSSHub'
        runs-on: ubuntu-latest
        steps:
        -
            name: Checkout
            uses: actions/checkout@v2
        -
            name: Set up Docker Buildx
            id: buildx
            uses: crazy-max/ghaction-docker-buildx@v1
            with:
                buildx-version: latest
        -
            name: Build dockerfile (without push)
            run: |
                docker buildx build \
                --platform=linux/amd64,linux/arm/v7,linux/arm64 \
                --output "type=image,push=false" \
                --file ./Dockerfile .
