name: Sync Fork

on:
  schedule:
  - cron: '11 3 * * *'
  workflow_dispatch:

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
    - uses: tgymnich/fork-sync@v1.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        owner: DIYgod
        base: master
        head: master
        # auto_approve: false
